Repository config4k/config4k, pull requests merged in 2022-08, with the labels that each got.

#130 Add documentation (powered by Jekyll)
  .github/workflows/build-test.yml
  .github/workflows/publish-releases.yml
  .github/workflows/publish-snapshots.yml
  docs/.gitignore
  docs/404.html
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  docs/_includes/head_custom.html
  docs/assets/example.png
  docs/index.html
  docs/index.md
  docs/install.md
  docs/params.json
  docs/stylesheets/github-light.css
  docs/stylesheets/normalize.css
  docs/stylesheets/stylesheet.css
  docs/supported-types.md
  docs/usage/delegated-properties.md
  docs/usage/deserialization/data-class.md
  docs/usage/deserialization/enum.md
  docs/usage/deserialization/index.md
  docs/usage/deserialization/map.md
  docs/usage/deserialization/nullable.md
  docs/usage/index.md
  docs/usage/serialization/index.md
  docs/usage/serialization/render-options.md
  docs/usage/serialization/string.md
  src/test/kotlin/io/github/config4k/DocExamples.kt
Labels: maintenance

#131 Configure baseurl for docs
  .github/workflows/publish-releases.yml
  .github/workflows/publish-snapshots.yml
  docs/_config.yml
Labels: maintenance

#135 Renovate shouldn't update Ruby dependencies for Jekyll docs
  renovate.json
Labels: maintenance

#136 Update README and CONTRIBUTING for documentation
  CONTRIBUTING.md
  README.md
  build.gradle.kts
  src/test/kotlin/io/github/config4k/TestDocumentedExamples.kt
Labels: maintenance

#137 Migrate to JGitVer plugin
  build.gradle.kts
  gradle/libs.versions.toml
Labels: maintenance

#138 Enable Kotlin Binary compatibility validator
  api/config4k.api
  build.gradle.kts
  gradle/libs.versions.toml
Labels: maintenance

#140 Use Kotlin Explicit API Mode and `allWarningsAsErrors = true`
  build.gradle.kts
  src/main/kotlin/io/github/config4k/Config4kException.kt
  src/main/kotlin/io/github/config4k/CustomType.kt
  src/main/kotlin/io/github/config4k/Extension.kt
  src/main/kotlin/io/github/config4k/TypeReference.kt
  src/main/kotlin/io/github/config4k/readers/SelectReader.kt
Labels: maintenance

#110 allow private access with getConfigMap
  src/main/kotlin/io/github/config4k/GetConfigMap.kt
  src/test/kotlin/io/github/config4k/TestToConfigForArbitraryType.kt
Labels: bug

#141 #101 Support Java Bean notation
  src/main/kotlin/io/github/config4k/readers/JavaBeanReader.kt
  src/main/kotlin/io/github/config4k/readers/SelectReader.kt
  src/test/java/io/github/config4k/TestJavaBean.java
  src/test/kotlin/io/github/config4k/TestArbitraryType.kt
Labels: enhancement

#144 #103 Fix special characters in Map keys
  src/main/kotlin/io/github/config4k/Extension.kt
  src/test/kotlin/io/github/config4k/TestToConfigForCollection.kt
Labels: bug

#146 #100 Fix serialization `java.time.Duration`
  src/main/kotlin/io/github/config4k/Extension.kt
  src/test/kotlin/io/github/config4k/TestArbitraryType.kt
  src/test/kotlin/io/github/config4k/TestToConfigForArbitraryType.kt
Labels: bug

#147 #88 Support `java.net.URL`
  docs/supported-types.md
  src/main/kotlin/io/github/config4k/Extension.kt
  src/main/kotlin/io/github/config4k/readers/SelectReader.kt
  src/main/kotlin/io/github/config4k/readers/URLReader.kt
  src/test/kotlin/io/github/config4k/TestArbitraryType.kt
  src/test/kotlin/io/github/config4k/TestToConfigForArbitraryType.kt
Labels: enhancement

#106 Added default value at extension Config.extract
  CONTRIBUTING.md
  docs/usage/deserialization/default-values.md
  docs/usage/deserialization/enum.md
  src/main/kotlin/io/github/config4k/Extension.kt
  src/test/kotlin/io/github/config4k/DocExamples.kt
  src/test/kotlin/io/github/config4k/TestConfig4kException.kt
  src/test/kotlin/io/github/config4k/TestExtension.kt
  src/test/kotlin/io/github/config4k/TestNullable.kt
Labels: enhancement

#148 Fix release GitHub action
  .github/workflows/build-test.yml
  .github/workflows/publish-releases.yml
  .github/workflows/publish-snapshots.yml
Labels: maintenance
